### ISSUE TITLE
Economy Improvements

### ISSUE THREAD

**Issue by ryantheleach** [FoundationDriven/Foundation#41]
Is the economy API just for foundation, or is it expected to be a vault replacement for sponge?

If it's intended on being a vault replacement, I'd recommend adding a concept of a transaction between 2 users, or 2 bank accounts.

transactions should be asynchronous, allowing for cross-server or web based transactions.

They should also allow multiple currencies, as well as items, more and more servers are leaning towards physical items replacing virtual currencies, this should be supported in some manner.

A bank account should be implementable by any bank account provider, a users inventory, backpack, virtual chest, enderchest, or some other real location in the world that gets fed by a virtual queue.

A transaction when made, should contain the world, location and server allowing for the implementing plugin to filter based on region, world, server to manage as appropriate.

It should also contain where it was transferred from, multiple bank accounts, players inventories etc so refunds are possible.

users should be identified by UUID, as should the "bank account" identities.

A broker basically validates that a transaction can take place, to make sure that cross-world stuff can/can't happen.

Doing this should account for all the faults vault had, but there is probably more functionality that I am missing.

Transactions can link to a second transaction, should the first transaction fail, the second transaction is reversed.

A reversed transaction must be allowed to happen (negative balances, queued inventory changes if an inventory is too full) as opposed to a transaction which can be cancelled depending on the response from a shop/player.

Player initiates trade with a shop, A new transaction from the shop to the player is created, requesting an amount of currency, whichever plugin the broker decides deals with the currency requested which crafts another transaction containing the items requested.

The payment is then sent to the shop, who holds it and sends back the product purchased to the player via a third and final transaction.

Should any stage of this transaction chain fail, the previous steps are reversed.

Once the transaction has completed, the shop plugin transfers the amount paid to the player who owns the shop, either queueing it, holding it in a chest, or transferring it virtually.

If virtually, a broker checks the transactions options to work out the best place to deposit the amount

**Comment by ryantheleach** [comment]
Moved from https://github.com/FoundationDriven/Foundation/issues/40 by request

**Comment by OscarOrSomething** [comment]
Honestly couldn't be bothered with GenMyModel for some reason so here is the design I drafted:
# Flow
**Request from API (async or sync)** >>> 

**Check if account(s) are already frozen, if so async called if applicable and flow ends**

**Account(s) frozen**

**Transaction object created** >>> 

**Broker created to handle Transaction** >>> 

**Broker finds applicable rules (filtered by world, plugin, currency etc.)** >>>

**Broker checks for any violation in rules** >>>

> **If found, violations are thrown as a RuleViolation Error, the request is logged, account(s) unfrozen, async called if applicable and flow ends**

**Otherwise flow continues** >>>

**Broker 'signs' the transaction and it goes through** >>>

**Flow ends, account(s) unfrozen and async called if applicable**

# Accounts
An account is instead an interface, this is implemented by modules and is passed in as an argument to any Action.
## Attributes
All are private.
### amount
An integer representing the amount, self explanatory.
### uuid
Universal Unique Identifier, Self explanatory
### frozen
boolean representing whether or not the amount is locked, this is true when a transaction is happening
## Methods
All are public
### forceUpdate
Forces an update (called after any transaction)
### take
Takes from the ammount
### give
Adds to the amount
### getAmount, getUUID
Self explanatory
### setAmount
Self explanatory
### freeze, unfreeze
Freezes or unfreezes the account

# Action
Used to express what a transaction will do.
## Attributes
### type
The type of transaction (ActionType enum: GIVE_FROM_SECONDARY, TAKE_FROM_SECONDARY, GIVE, TAKE, SET)
### target
The target of this transaction (an account)
### secondaryTarget
The secondary target of this transaction, used in GIVE_FROM_SECONDARY and TAKE_FROM_SECONDARY
### amount
The value to operate with.
### world, plugin and time
Self explanatory
## Methods
### Constructor
Self explanatory
# TransactionManager
Main entry point, used to start transactions
## Attributes
### currentTransactions
List of transactions, self explanatory
## Methods
### perform and performAsync
Starts a transaction based on the given Action, method is needed for transactionAsync
# Transaction
## Attributes
### action
The action that this transaction is based on.
### broker
The broker for this transaction.
### callback
Set when the async constructor is used.
## Methods
### constructor
Sets the action and starts broking
### broke
Creates the broker and Brokes the transaction.
# Broker
## Attributes
### transaction
The transaction this is for
### applicableRules
List of applicable rules, null when not calculated
### rulesPassed
Boolean, self explanatory
## Methods
### constructor
Sets the transaction then Calls calculateRules and checkRules 
### calculateRules
Calculates the rules that apply to this transaction and sets the applicableRules.
### checkRules
Checks the criteria of the rules are satisfied.

# Rule
## Attributes
### Matcher
This is a string that has a format similar to the examples below, it is used to specify what transactions this rule applies to

*Simple one plugin matcher*
```
PLUGIN='Suspicious Plugin';
```
*OR*
```
PLUGIN='Suspicious Plugin 1'|'Suspicious Plugin 2';
```
*Multiple matching criteria (works with previous example)*
```
PLUGIN='Suspicious Plugin 1'|'Suspicious Plugin 2';WORLD='Criminal World 1'|'Criminal World 2';
```
### Criteria
This is a string that has a format similar to the examples below, it is used to specify the criteria the transactions must match

*Amount Greater than*
```
AMOUNT>10;
```
*Amount Less than*
```
AMOUNT<100;
```
*Amount Equals*
```
AMOUNT=21;
```
*ActionType (Works with OR as above)*
```
TYPE=GIVE|TAKE;
```
*Amount also works with OR*
```
AMOUNT>10|<100|=21;
```
*or AND (Not at the same time)*
```
AMOUNT>10&<100&=21
```

# Notes

Nothing is saved to the config.
500 words In case you're interested, Look good?

**Comment by exstar** [comment]
Looks good to me, we'll discuss a few points (Foundation in general) next week, when i'm less busy.

**Comment by ryantheleach** [comment]
Only thing that appears to be missing is multiple currencies.

**Comment by OscarOrSomething** [comment]
I'll add multiple currencies soon, I'm snowed in so soon.

**Comment by OscarOrSomething** [comment]
I'll start coding this.
